### PR TITLE
Update network.md

### PR DESCRIPTION
**Pull request by mbo18**
Error in documentation in example to setup a static IP address.
Must be a ";" instead of a "," between IP/Mask and Gateway.

Solve https://community.home-assistant.io/t/setting-a-static-ip-on-hassio-hassos/63378

### CODE REVIEW

**Comment by mbo18** [comment]
Solve #414

**Comment by pvizeli** [comment]
Which version of HassOS do you use?

**Comment by mbo18** [comment]
HassOS 2.12

**Comment by mbo18** [comment]
@pvizeli feel free to close this PR if not relevant. This was tested on my system using HassOS 2.12. Not tested on 3.5 but can do it. 
Thanks

**Comment by pvizeli** [comment]
Both work, anyway for conistents let merge it

**Pull request merged**
