### PR TITLE
Intel NUC support

### PR DESCRIPTION
**Pull request by jvanderneutstulen**
This PR adds support Hassos on the Intel NUC (#214) and compatible (probably anything modern with intel or realtek nic and/or intel wifi). The configuration is based the ova target.

Differences:
- Add igb nic driver (see #197)
- Add wifi for modern intel wifi cards
- Add firmware for i915 chip for (hopefully) better power management
- Enable power savings on HD audio
- Add rng-tool to improve available entropy on boot

Tested:
- Intel NUC5CPYH  
- Gigabyte GB-BPCE-3455  (needs 'nomodeset' in cmdline.txt if you want a console)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @jvanderneutstulen, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassos#288).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
We look that we use the same feature on every platform. Can you add BR2_PACKAGE_RNG_TOOLS to other config files?

**Comment by jvanderneutstulen** [comment]
> We look that we use the same feature on every platform. Can you add BR2_PACKAGE_RNG_TOOLS to other config files?

Shouldn't we move this to a separate PR/issue? For OVA the kernel config also needs changes.

**Comment by pvizeli** [comment]
@jvanderneutstulen yes, sure

**Comment by pvizeli** [comment]
Good work 👍

**Pull request merged**
