### PR TITLE
Update documentation for a static IPV4 address via nmcli

### PR DESCRIPTION
**Pull request by borpin**
In looking for a way to set a static IPV4 address on a Esxi hosted Hassio, I discovered this method using the NetworkManager CLI (nmcli).  I felt it might be good to document it.

Happy for the formatting to be modified to suit local convention.

I cannot be more specific about how to get into the base OS as I don't know!

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @borpin, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassos#199).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by borpin** [comment]
Done.  I could see I needed to from the checks, but there was no link to that location :smile:

**Comment by pvizeli** [comment]
Thanks

**Comment by mattnewham** [comment]
I think this should also be updated to reference setting DNS and gateway, as with the current nmcli config you will only get local LAN access with no DNS from the docker containers etc

**Comment by klrock** [comment]
I am trying to change the ipv4 ip address of my supervised Home Assistant installed on a win 10 VirtualBox.  Using cli in the console, when I enter "`# nmcli con edit “HassOS default”` " I get not recognized and am therefore unable to edit or change any settings.  Is this method only for Hassio?  Is there an alternate method for my installation?

**Pull request merged**
