### PR TITLE
Rpi update

### PR DESCRIPTION
**Pull request by pvizeli**
Fix: #435 #451 #447

### CODE REVIEW

**Comment by sblantipodi** [comment]
when this fix is supposed to be released? 
will it be released in the next HA release?

**Comment by eftibug** [comment]
Could you please help me to learn how to update to the fixed version?
Thanks!

**Comment by iBobik** [comment]
@pvizeli Could we ask for minor version release with this, please? I think this issues are critical enough to not wait for regular release.

**Comment by pvizeli** [comment]
There is a bug they need first solved: https://github.com/raspberrypi/firmware/issues/1236

**Pull request merged**
