### PR TITLE
Fix ring buffer errors by applying ODroid Patch

### PR DESCRIPTION
**Pull request by TonyApuzzo**
Fix for https://github.com/home-assistant/hassos/issues/354

See: https://github.com/hardkernel/linux/commit/66d3985b4a0da52bbaf6da6d0a7b42890eef5b42

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @TonyApuzzo, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassos#355).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by jvanderneutstulen** [comment]
Can't you just use the coherent_pool parameter (see https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html). Add `coherent_pool=1M` to the cmdline.txt ?

**Comment by TonyApuzzo** [comment]
I didn't know that was an option, I will try it as soon as I can (which will be a day or two because of ♥day.)

**Comment by pvizeli** [comment]
For me is fine to patch this

**Pull request merged**
