### PR TITLE
create cache dir if not exist

### PR DESCRIPTION
**Pull request by moshe010**
Signed-off-by: Moshe Levi <moshele@mellanox.com>

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @moshe010, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassos#471).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
docker create the cache dir if not exists and now you can't set a custom cache directory over env

**Comment by moshe010** [comment]
it didn't create on rhel 8.0 (which is using podman) ...

**Comment by pvizeli** [comment]
I'm fine to create the folder but this destroy the function to overwrite the path over ENV variable in bash style way. If you fix that, we can merge this

**Comment by moshe010** [comment]
sure I will fix that

**Pull request merged**
