### PR TITLE
Update config.txt

### PR DESCRIPTION
**Pull request by kwdavidson**
Enable SPI and I2C by default.

### CODE REVIEW

**Comment by pvizeli** [comment]
That have no effect, we build this dynamic. Please explain your change request a bit more.

**Comment by kwdavidson** [comment]
There are Hass-supported devices that use the SPI and I2C ports on a Raspberry Pi. Since these ports are disabled by default, it forces the user to figure out how to get into the boot partition and modify the config.txt file. If they were on by default, things would just work.

**Comment by pvizeli** [comment]
Is that the default on rasbian?

buildroot-external is the layer where we can change things.

**Comment by pvizeli** [comment]
Put it in post build script of rpi

**Pull request closed without merging**
